theme: jekyll-theme-minimal
title: Code for Baltimore
logo: /assets/img/banner.png
description: We are civic hackers interested in contributing to open data and open source in Baltimore.
show_downloads: false
google_analytics:
